version: "3.8"

services:
  db:
    image: postgres:15
    container_name: learning_tracker_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: learning_tracker
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"       # your machine:5432 → container:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data   # data stays even if container stops

volumes:
  postgres_data: