from datetime import datetime
from typing import Literal

from pydantic import BaseModel, EmailStr, Field, field_validator


class UserBase(BaseModel):
    email: EmailStr = Field(..., examples=["john.doe@example.com"])
    name: str = Field(
        ...,
        min_length=2,
        max_length=100,
        pattern=r"^[A-Za-z ]+$",
        examples=["John Doe"],
    )
    contact: str = Field(
        ...,
        pattern=r"^\+91-[6-9]\d{9}$",
        examples=["+91-9988990099"],
    )
    role_id: Literal[1, 2]


class UserRegistration(UserBase):
    password: str = Field(
        ...,
        min_length=8,
        max_length=50,
        examples=["Password@123"],
    )

    @field_validator("password")
    @classmethod
    def validate_password(cls, value: str) -> str:
        if not any(char.isupper() for char in value):
            raise ValueError("Password must contain at least one uppercase letter")

        if not any(char.islower() for char in value):
            raise ValueError("Password must contain at least one lowercase letter")

        if not any(char.isdigit() for char in value):
            raise ValueError("Password must contain at least one digit")

        special_chars = "!@#$%^&*()_+-=[]{}|;:,.<>?"

        if not any(char in special_chars for char in value):
            raise ValueError("Password must contain at least one special character")

        return value


class UserResponse(BaseModel):
    # user_id is now the PK — generated by DB as learn-0001
    user_id: str
    email: EmailStr
    name: str
    contact: str
    role_id: int
    is_active: bool
    created_at: datetime

    model_config = {"from_attributes": True}


class UserAlreadyExistsResponse(BaseModel):
    detail: str = "User with this email or contact already exists"